services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\DoctrineSnowflakeBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  Tourze\DoctrineSnowflakeBundle\Service\:
    resource: '../../Service/'

  Godruoyi\Snowflake\Snowflake:
    factory: [ '@Tourze\DoctrineSnowflakeBundle\Service\ResolverFactory', 'generate' ]
    public: true
